server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul:
  #ignored-services: microservicecloud-dept        #禁掉通过服务名microservicecloud-dept访问入口
  ignored-services: "*"                            #禁掉all服务名访问入口
  routes:
    mydept:
      path: /mydept/**
      serviceId: microservicecloud-dept       #  /mydept/**  转到微服务的  /**
    dept:
      path: /dept/**
      serviceId: microservicecloud-dept
      stripPrefix: false                      # 直接将 /dept/** 转到微服务的 /dept/**



info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

